name: UGALY
version: "3.0"
license: "GPL-3.0-or-later"
date: 2021-07-22
description: |
    Universal Groups Acting LocallY

authors:
    - name: Khalil Hannouch
      url: https://www.newcastle.edu.au/profile/khalil-hannouch
    - name: Stephan Tornier
      url: https://www.newcastle.edu.au/profile/stephan-tornier

maintainers:
    - name: Stephan Tornier
      url: https://www.newcastle.edu.au/profile/stephan-tornier

GAP: ">= 4.10.2"

www: https://torniers.github.io/UGALY
readme: README.md
packageinfo: https://torniers.github.io/UGALY/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/torniers/UGALY/releases/download/v3.0/UGALY-3.0.tar.gz

abstract: |

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    universal group, local action, regular tree, groups acting on trees, locally compact group, totally disconnected.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HT21</span>]   <b class='BibAuthor'>Hannouch, K. and Tornier, S.</b>,
     <i class='BibTitle'>UGALY, Universal Groups Acting LocallY,
             Version 3.0</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://torniers.github.io/UGALY">https://torniers.github.io/UGALY</a></span>.
    </p>
    

bibtex: |
    @misc{ UGALY3.0,
      author =           {Hannouch, K. and Tornier, S.},
      title =            {{UGALY},  Universal  Groups  Acting LocallY, {V}ersion
                          3.0},
      month =            {Jul},
      year =             {2021},
      note =             {Refereed GAP package},
      howpublished =     {\href               {https://torniers.github.io/UGALY}
                          {\texttt{https://torniers.github.io/}\discretionary
                          {}{}{}\texttt{UGALY}}},
      keywords =         {universal  group;  local  action; regular tree; groups
                          acting   on  trees;  locally  compact  group;  totally
                          disconnected},
      printedkey =       {HT21}
    }

