name: UGALY
version: "4.0.3"
license: "GPL-3.0-or-later"
date: 2022-07-14
description: |
    Universal Groups Acting LocallY

authors:
    - name: Khalil Hannouch
      url: https://www.newcastle.edu.au/profile/khalil-hannouch
    - name: Stephan Tornier
      url: https://www.newcastle.edu.au/profile/stephan-tornier

maintainers:
    - name: Stephan Tornier
      url: https://www.newcastle.edu.au/profile/stephan-tornier

GAP: ">= 4.10.2"

needed-pkgs:
    - name: "fga"
      version: ">= 1.0"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"

www: https://gap-packages.github.io/UGALY
readme: README.md
packageinfo: https://gap-packages.github.io/UGALY/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/UGALY/releases/download/v4.0.3/UGALY-4.0.3.tar.gz

abstract: |
    <span class="pkgname">UGALY</span> (Universal Groups Acting LocallY) is a <span class="pkgname">GAP</span> package that provides methods to create, analyse and find local actions of generalised universal groups acting on locally finite regular trees, following Burger-Mozes and Tornier.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    universal group, local action, regular tree, groups acting on trees, locally compact group, totally disconnected.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HT22</span>]   <b class='BibAuthor'>Hannouch, K. and Tornier, S.</b>,
     <i class='BibTitle'>UGALY, Universal Groups Acting LocallY,
             Version 4.0.3</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/UGALY">https://gap-packages.github.io/UGALY</a></span>.
    </p>
    

bibtex: |
    @misc{ UGALY4.0.3,
      author =           {Hannouch, K. and Tornier, S.},
      title =            {{UGALY},  Universal  Groups  Acting LocallY, {V}ersion
                          4.0.3},
      month =            {Jul},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/UGALY}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{UGALY}}},
      keywords =         {universal  group;  local  action; regular tree; groups
                          acting   on  trees;  locally  compact  group;  totally
                          disconnected},
      printedkey =       {HT22}
    }

